config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    omniauth_callbacks: 'omniauth_callbacks'
  }
  resources :ai_components, only: [:create, :show, :index, :destroy] do
    scope module: :ai_components do
      resources :additions, only: [:create]
      resources :edit_code, only: [:new, :create], controller: :edit_code
    end
  end
  resources :subscriptions, only: [:new, :create, :edit]
  namespace :subscriptions do
    resource :payment_intent, only: [:create], controller: 'payment_intent'
    resource :success, only: [:show], controller: "success"
    resource :cancel, only: [:create], controller: "cancel"
  end
  resource :purchase, only: [:new], controller: :purchase

  namespace :purchase do
    resource :payment_intent, only: [:create], controller: 'payment_intent'
    resource :success, only: [:show], controller: "success"
  end

  namespace :users do
    resource :deactivate, only: [:show], controller: :deactivate
  end
  resources :users do
    scope module: :users do
      resource :unsubscribe_email, only: [:create, :show], controller: "unsubscribe_email"
    end
  end
  resource :dashboard, only: [:show], controller: :show
  post "/webhook_events/:source", to: "webhook_events#create"
  get "/admin", to: "admins#index"
  namespace :admins do
    resources :users, only: [:index] do
      post "listen_to_subscription", to: "users#listen_to_subscription"
      post "ignore_subscription", to: "users#ignore_subscription"
    end
    resources :component_packs do
      post "make_featured", to: "component_packs#make_featured"
      post "turn_off_featured", to: "component_packs#turn_off_featured"
      scope module: :component_packs do
        resources :ai_components, only: [:create]
      end
    end
    resources :emails, only: [:new, :create, :index]
    resources :ai_components, only: [:index, :show]
  end
  resources :free_component_packs, only: [:show]
  resource :sign_in_modal, only: [:create], controller: 'sign_in_modal'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "dashboard#show"
end

app/views/admins/index.html.erb
<div class="w-full min-h-screen bg-gradient-to-r from-indigo-500 to-pink-500 p-4">
  <h1 class="text-gray-200 text-center text-3xl mt-8"> Admin </h1>
  
  <div class=" w-full mx-auto grid md:grid-cols-3 lg:grid-cols-5 gap-8">
    <p class="text-gray-100 mt-3 h-24 w-full bg-gray-500/75 text-xl flex items-center justify-center rounded-lg"> <%= User.all.count %> users joined the site so far  </p>

    <p class="text-gray-100 mt-3 h-24 w-full bg-gray-500/75 text-xl flex items-center justify-center rounded-lg"> <%= @active_subscriptions %> users actively subscribed</p>
  
    <p class="text-gray-100 mt-3 h-24 w-full bg-gray-500/75 text-xl flex items-center justify-center rounded-lg"> <%= User.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now).count %> users joined the site today </p>

    <p class="text-gray-100 mt-3 h-24 w-full bg-gray-500/75 text-xl flex items-center justify-center rounded-lg"> <%= number_to_currency(Subscription.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now, status: :active).count * 4.99) %> increase in MRR </p>
    
    <p class="text-gray-100 mt-3 h-24 w-full bg-gray-500/75 text-xl flex items-center justify-center rounded-lg"> <%= Subscription.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now, status: :active).count %> new subscriptions today</p>

    <%= link_to admins_ai_components_path(date: Time.zone.now) do %>
      <p class="text-gray-100 mt-3 h-24 w-full bg-gray-500/75 text-xl flex items-center justify-center rounded-lg"> <%= AiComponent.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now).count %> components created today</p>
    <% end %>
    <p class="text-gray-100 mt-3 h-24 w-full bg-gray-500/75 text-xl flex items-center justify-center rounded-lg"> <%= AiComponent.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now).where.not(user_id: nil).count %> created by authed user today</p>

    <p class="text-gray-100 mt-3 h-24 w-full bg-gray-500/75 text-xl flex items-center justify-center rounded-lg"> <%= @components_by_subscribed %> created by paid user today</p>
    
  </div>
  
  <div id="actions" class="max-w-5xl w-full mx-auto mt-8 grid grid-cols-4 gap-8">
    <%= link_to "Component packs", admins_component_packs_path, class: "text-xl text-gray-200 bg-green-500 rounded-lg p-2" %>
    <%= link_to "New Email", new_admins_email_path, class: "text-xl text-purple-200 bg-purple-500 rounded-lg p-2" %>
    <%= link_to "All components", admins_ai_components_path, class: "text-xl text-purple-200 bg-purple-500 rounded-lg p-2" %>
  </div>

  <div class="max-w-5xl w-full mx-auto mt-8">
    <p class="text-gray-100 mt-3"> <%= number_to_currency(@active_subscriptions.to_f * 4.99) %> monthly revenue 😁🥳 </p>
    <%= turbo_frame_tag :users, src: admins_users_path %>
  </div>
</div>