config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    omniauth_callbacks: 'omniauth_callbacks'
  }
  resources :ai_components, only: [:create, :show, :index, :destroy] do
    scope module: :ai_components do
      resources :additions, only: [:create]
      resources :edit_code, only: [:new, :create], controller: :edit_code
    end
  end
  resources :subscriptions, only: [:new, :create, :edit]
  namespace :subscriptions do
    resource :payment_intent, only: [:create], controller: 'payment_intent'
    resource :success, only: [:show], controller: "success"
    resource :cancel, only: [:create], controller: "cancel"
  end
  resource :purchase, only: [:new], controller: :purchase

  namespace :purchase do
    resource :payment_intent, only: [:create], controller: 'payment_intent'
    resource :success, only: [:show], controller: "success"
  end

  namespace :users do
    resource :deactivate, only: [:show], controller: :deactivate
  end
  resources :users do
    scope module: :users do
      resource :unsubscribe_email, only: [:create, :show], controller: "unsubscribe_email"
    end
  end
  resource :dashboard, only: [:show], controller: :show
  post "/webhook_events/:source", to: "webhook_events#create"
  get "/admin", to: "admins#index"
  namespace :admins do
    resources :users, only: [:index] do
      post "listen_to_subscription", to: "users#listen_to_subscription"
      post "ignore_subscription", to: "users#ignore_subscription"
    end
    resources :component_packs do
      post "make_featured", to: "component_packs#make_featured"
      post "turn_off_featured", to: "component_packs#turn_off_featured"
      scope module: :component_packs do
        resources :ai_components, only: [:create]
      end
    end
    resources :emails, only: [:new, :create, :index]
    resources :ai_components, only: [:index, :show]
  end
  resources :free_component_packs, only: [:show]
  resource :sign_in_modal, only: [:create], controller: 'sign_in_modal'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "dashboard#show"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
  has_one_attached :avatar
  after_create_commit :register_stripe_customer
  has_many :ai_components
  has_many :user_roles
  has_one :subscription
  has_secure_token :email_token

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.password = Devise.friendly_token.first(6)
      user.email = auth.info.email
      user.full_name = auth.info.name
      user.avatar_url = auth.info.image
    end
  end

  def self.free_users
    includes(:subscription).where.not(subscription: { status: :active }).or(
      includes(:subscription).where(subscription: { id: nil }))
  end

  def self.paid_users
    includes(:subscription).where(subscription: { status: :active })
  end

  def avatar_display
    if avatar.attached?
      avatar
    elsif avatar_url.present?
      avatar_url
    else
      "https://gravatar.com/avatar/c553f5893997262b965cb8fa9e34df6a?s=200&d=mp&r=g"
    end
  end

  def register_stripe_customer
    RegisterStripeCustomerJob.perform_later(id)
  end

  def active_subscription
    Subscription.where(user: self, status: :active).first
  end

  def google_authed?
    uid.present? && provider == "google_oauth2"
  end

  def paid_account?
    active_subscription.present? || purchased_lifetime_membership?
  end
  # User roles

  def admin?
    user_roles.find_by(role: Role.admin_role).present?
  end
end

app/controllers/admins/users_controller.rb
module Admins
  class UsersController < Admins::BaseController
    before_action :set_user, only: [:listen_to_subscription, :ignore_subscription]
    def index
      @users = User.all.order(created_at: :desc)
    end

    def listen_to_subscription
      return head :ok if !@user.active_subscription
      @user.active_subscription.update(ignore_subscription: false)
      render turbo_stream: turbo_stream.replace(ActionView::RecordIdentifier.dom_id(@user, :dropdown), partial: "dropdown", locals: { user: @user })
    end

    def ignore_subscription
      return head :ok if !current_user.active_subscription
      @user.active_subscription.update(ignore_subscription: true)
      render turbo_stream: turbo_stream.replace(ActionView::RecordIdentifier.dom_id(@user, :dropdown), partial: "dropdown", locals: { user: @user })
    end

    private

    def set_user
      @user = User.find(params[:user_id])
    end

  end
end

app/controllers/users/deactivate_controller.rb
class Users::DeactivateController < ApplicationController
  def show;end
end

app/controllers/users/unsubscribe_email_controller.rb
module Users
  class UnsubscribeEmailController < ApplicationController
    before_action :set_user
    def create
      @user.update(recieve_email_notifications: false)
      redirect_to user_unsubscribe_email_path(@user)
    end
    
    def show; end

    private

    def set_user
      @user = User.find_by_email_token(params[:user_id])
    end
  end
end

app/views/admins/users/_dropdown.html.erb
<div class="absolute h-56 w-56 bg-gray-400/75 backdrop-blur rounded-lg hidden z-50" id="<%= dom_id(user, :dropdown) %>" data-dropdown-target="menu">
  <% if user.active_subscription&.ignore_subscription? %>
    <div class="flex flex-col items-center gap-4 p-2">
      <%= link_to "Use subscripton in reports", admins_user_listen_to_subscription_path(user), class: "text-gray-900 text-lg", data: { turbo_method: :post } %>
    </div>
  <% else %>
    <div class="flex flex-col items-center gap-4 p-2">
      <%= link_to "Ignore Subscription", admins_user_ignore_subscription_path(user), class: "text-gray-900 text-lg", data: { turbo_method: :post } %>
    </div>
  <% end %>
</div>

app/views/admins/users/index.html.erb
<%= turbo_frame_tag :users do %>
  <div class="flex flex-col gap-4 mt-4 border-b-2 border-gray-200">
    <% @users.each do |user| %>
      <div class="w-full flex gap-4">
        <span class="text-gray-200 text-xl mr-auto"> 
          <%= user.full_name || "No name" %> 
        </span>
        <span class="text-gray-200 text-xl"> 
          <%= user.email %> 
        </span>
        <div class="text-gray-200 text-xl"> 
          <% if user.google_authed? %>
            <span class="bg-indigo-500 text-indigo-50 p-1 rounded-lg"> 
              Google Authed
            </span>
          <% else %>
          <span class="text-indigo-50 p-1 rounded-lg"> 
              Regular sign up
            </span>
          <% end %>
        </div>

        <div class="text-gray-200 text-xl"> 
          <% if user.active_subscription.present? %>
            <span class="bg-green-500 text-green-50 p-1 rounded-lg"> 
              Subscribed
            </span>
          <% else %>
            <span class="bg-red-800 text-red-50 p-1 rounded-lg"> 
              No membership
            </span>
          <% end %>
        </div>

        <% if user.active_subscription %>
          <div data-controller="dropdown" data-action="click@window->dropdown#closeUnlessDropdown" class="relative">
            <%= link_to "#", data: { action: "dropdown#toggle" } do %>
              <%= render Icons::EllipsisVerticalComponent.new %>
            <% end %>
            <%= render "dropdown", user: user %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>