config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    omniauth_callbacks: 'omniauth_callbacks'
  }
  resources :ai_components, only: [:create, :show, :index, :destroy] do
    scope module: :ai_components do
      resources :additions, only: [:create]
      resources :edit_code, only: [:new, :create], controller: :edit_code
    end
  end
  resources :subscriptions, only: [:new, :create, :edit]
  namespace :subscriptions do
    resource :payment_intent, only: [:create], controller: 'payment_intent'
    resource :success, only: [:show], controller: "success"
    resource :cancel, only: [:create], controller: "cancel"
  end
  resource :purchase, only: [:new], controller: :purchase

  namespace :purchase do
    resource :payment_intent, only: [:create], controller: 'payment_intent'
    resource :success, only: [:show], controller: "success"
  end

  namespace :users do
    resource :deactivate, only: [:show], controller: :deactivate
  end
  resources :users do
    scope module: :users do
      resource :unsubscribe_email, only: [:create, :show], controller: "unsubscribe_email"
    end
  end
  resource :dashboard, only: [:show], controller: :show
  post "/webhook_events/:source", to: "webhook_events#create"
  get "/admin", to: "admins#index"
  namespace :admins do
    resources :users, only: [:index] do
      post "listen_to_subscription", to: "users#listen_to_subscription"
      post "ignore_subscription", to: "users#ignore_subscription"
    end
    resources :component_packs do
      post "make_featured", to: "component_packs#make_featured"
      post "turn_off_featured", to: "component_packs#turn_off_featured"
      scope module: :component_packs do
        resources :ai_components, only: [:create]
      end
    end
    resources :emails, only: [:new, :create, :index]
    resources :ai_components, only: [:index, :show]
  end
  resources :free_component_packs, only: [:show]
  resource :sign_in_modal, only: [:create], controller: 'sign_in_modal'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "dashboard#show"
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  enum status: [:inactive, :active]
end

app/controllers/subscriptions/cancel_controller.rb
module Subscriptions
  class CancelController < ApplicationController
    def create
      subscription = current_user.subscription
      Stripe::Subscription.delete(subscription.stripe_subscription_id)
      if subscription.destroy!
        redirect_to root_path, notice: "Your subscription was cancelled"
      end
    end
  end
end

app/controllers/subscriptions/payment_intent_controller.rb
module Subscriptions
  class PaymentIntentController < ApplicationController
    def create
      if !current_user.customer_id.present?
        stripe_customer = Stripe::Customer.create({
          description: 'Registered user for Tailwind Genius account.',
          email: current_user.email,
          name: current_user.full_name
        })
        current_user.customer_id = stripe_customer.id
        current_user.save!
      end

      subscription = Stripe::Subscription.create(
        customer: current_user.customer_id,
        items: [{
          price: Rails.application.credentials.dig(:stripe, :monthly_subscription_price),
        }],
        payment_behavior: 'default_incomplete',
        payment_settings: {save_default_payment_method: 'on_subscription'},
        expand: ['latest_invoice.payment_intent'],
        metadata: {
          user_id: current_user.id,
        },
      )


      respond_to do |format|
        format.json {
          render json: { 
            subscriptionId: subscription.id, 
            clientSecret: subscription.latest_invoice.payment_intent.client_secret 
          }
        }
      end
    end
  end
end

app/controllers/subscriptions/success_controller.rb
module Subscriptions
  class SuccessController < ApplicationController
    def show; end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!, only: [:edit]

  def new
    redirect_to root_path, notice: "You already have an active subscription" if current_user&.active_subscription
    if !current_user
      cookies["user_return_to"] = request.original_url
      session[:return_to] = request.original_url
      authenticate_user!
    end
  end

  def edit
    @subscription = Stripe::Subscription.retrieve(
      current_user.active_subscription.stripe_subscription_id,
    )
  end
end

app/views/subscriptions/edit.html.erb
<div class="p-3 flex flex-col items-center pt-16">
  <h1 class="text-2xl text-gray-900 mb-4"> Manage your Subscription </h1>
  <div class="max-w-2xl w-full bg-gray-200 rounded-lg shadow-lg p-3 flex flex-col justify-between min-h-[40vh]">
    <div class="grid grid-cols-3 lg:grid-cols-4 gap-4">
      <div>
        <p class="text-gray-900"> Renews on </p>
        <p class="text-gray-700"> <%= Time.at(@subscription.current_period_end).strftime("%b %-d, %Y") %> </p>
      </div>

      <div>
        <p class="text-gray-900"> Subscription Price </p>
        <p class="text-gray-700"> <%= number_to_currency 4.99 %> </p>
      </div>
    </div>
    <div class="flex justify-center">
      <%= link_to "Cancel Subscription", subscriptions_cancel_path, data: { turbo_method: :post, turbo_confirm: "Are you sure? You will need to resubscribe to continue to use Tailwind Genius" }, class: "bg-gray-500 text-gray-100 rounded-lg shadow-lg p-2" %>
    </div>
  </div>
</div>

app/views/subscriptions/new.html.erb
<div class="bg-gradient-to-b from-indigo-500 to-pink-500 h-[100vh]">
  <div class="grid lg:grid-cols-2">
    <div class="p-3 bg-gray-700 md:mt-32 max-w-lg mx-auto flex flex-col items-center justify-center p-3 h-[25rem] md:rounded-lg">
      <h1 class="text-3xl text-center text-indigo-200"> Upgrade your experience </h1>
      <p class="text-lg text-indigo-100 text-center mt-2 max-w-md"> 
        To continue using our tools and support us to create more features please enable your membership
        <span class="text-indigo-100"> <%= number_to_currency(4.99) %>/Monthly </span>
      </p>
      <p class="bg-indigo-500/75 text-indigo-100 text-center mt-2 max-w-md"> 
        For a limited time we are selling life time memberships for $49.99. 
        <%= link_to "Check it out here", new_purchase_path, class: "text-indigo-100 text-lg underline" %>
      </p>
    </div>

    <div class="md:mt-32">
      <div class="max-w-2xl w-full bg-gray-300/75 p-3">
        <form data-controller="stripe-element" 
        data-stripe-element-payment-intent-url-value="<%= subscriptions_payment_intent_path %>" data-stripe-element-success-url-value="<%= subscriptions_success_url(user_id: current_user.id) %>" data-action="stripe-element#submit">
          <div data-stripe-element-target="container">
            <span class="text-center text-lg text-gray-200">
              Preparing your secure checkout session <i class="fa fa-spin fa-spinner ml-2"> </i>
            </span>
          </div>
          <div class="mt-4">
            <button data-stripe-element-target="submit" class="text-gray-50 hidden bg-green-500 hover:bg-green-600 p-2 rounded-md w-full text-center shadow-md shadow-green-600 transition duration-300">
              <span> Pay now</span>
            </button>
          </div>
          <div data-stripe-element-target="message" class="hidden"></div>
        </form>
      </div>
    </div>
  </div>
</div>